Update clang-19-static-analysis.yml

diff --git a/.github/workflows/clang-19-static-analysis.yml b/.github/workflows/clang-19-static-analysis.yml
--- a/.github/workflows/clang-19-static-analysis.yml
+++ b/.github/workflows/clang-19-static-analysis.yml
@@ -24,9 +24,6 @@ jobs:
         protocol: ["current", "next"]
     steps:
       - name: Fix kernel mmap rnd bits
-        # Asan in llvm provided in ubuntu 22.04 is incompatible with
-        # high-entropy ASLR in much newer kernels that GitHub runners are
-        # using leading to random crashes: https://reviews.llvm.org/D148280
         run: sudo sysctl vm.mmap_rnd_bits=28
 
       - name: Probe Cache
@@ -82,33 +79,23 @@ jobs:
         if: steps.cache.outputs.cache-hit != 'true'
         run: cargo install --locked cargo-sweep --version 0.7.0
 
-     - name: Build with ci-build.sh
-       if: steps.cache.outputs.cache-hit != 'true'
-       run: |
-        # Set compiler environment variables for ci-build.sh
-        export CC='clang'
-        export CXX='clang++'
-        export CLANG_VERSION='19'
-        export SKIP_FORMAT_CHECK=1
-
-        # Run ci-build.sh with tests disabled and protocol specified
-        ./ci-build.sh --disable-tests --protocol ${{ matrix.protocol }}
-
-   - name: Compile overflow test
-     run: clang++ -fsanitize=address -g src/tests/overflow.cpp -o overflow_test
- 
-   - name: Run overflow test
-     run: ./overflow_test || echo "ASAN detected an error"
-
-          # Skip clang-format check since we don't have clang-format-12
+      - name: Build with ci-build.sh
+        if: steps.cache.outputs.cache-hit != 'true'
+        run: |
+          export CC='clang'
+          export CXX='clang++'
+          export CLANG_VERSION='19'
           export SKIP_FORMAT_CHECK=1
-
-          # Run ci-build.sh with tests disabled and protocol specified
           ./ci-build.sh --disable-tests --protocol ${{ matrix.protocol }}
+
+      - name: Compile overflow test
+        run: clang++ -fsanitize=address -g src/tests/overflow.cpp -o overflow_test
+
+      - name: Run overflow test
+        run: ./overflow_test || echo "ASAN detected an error"
 
       - uses: actions/cache/save@v4
         if: ${{ steps.cache.outputs.cache-hit != 'true' && github.ref_name == 'master' }}
         with:
           path: ${{ env.CACHED_PATHS }}
           key: ${{ steps.cache.outputs.cache-primary-key }}
-
